[workspace]
resolver = "2"
default-members = ["git-workon"]
members = [
  "git-workon",
  "git-workon-lib",
]

[workspace.package]
authors = ["Eric Eldredge <lettertwo@gmail.com>"]
edition = "2021"
homepage = "https://github.com/lettertwo/git-workon"
license = "MIT"
repository = "https://github.com/lettertwo/git-workon"
rust-version = "1.68.2"

[workspace.dependencies]
anyhow = "1.0.70"
assert_cmd = { version = "2.0.10", features = ["color", "color-auto"] }
assert_fs = { version = "1.0.12", features = ["color", "color-auto"] }
clap = { version = "4.2.1", features = ["derive", "color", "wrap_help", "unicode", "env"] }
clap-verbosity-flag = "2.0.1"
clap_complete = "4.2.0"
clap_complete_fig = "4.2.0"
clap_mangen = "0.2.10"
dialoguer = "0.10.3"
env_logger = "0.10.0"
git2_credentials = { version = "0.11.0", features = ["ui4dialoguer"] }
git2 = { version = "0.17", default-features = false }
log = "0.4.17"
predicates = { version = "3.0.2" }

[patch.crates-io]
git2_credentials = { git = "https://github.com/davidB/git2_credentials.git", branch = "dependabot/cargo/git2-tw-0.17" }
